SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [Comm].[GetOutbox] AS
BEGIN
  SELECT OutId, MessageText, MsgGuid FROM COMM.OutBox WHERE PulledAt IS NULL OR ISNULL(StatusCode,-2) < 0;
END
GO