SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [CRF].[GetFormActions]( @FormId INT )
AS
BEGIN
  SELECT * FROM dbo.MetaFormAction WHERE FormId=@FormId
END
GO

GRANT EXECUTE ON [CRF].[GetFormActions] TO [FastTrak]
GO