SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DbGetTextFieldSize]( @TableName sysname, @TableColumn sysname )
AS
BEGIN
  SELECT CHARACTER_MAXIMUM_LENGTH from INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = @TableName AND COLUMN_NAME=@TableColumn;
END
GO