SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GetStudyNames] AS
BEGIN
  SELECT StudyId,StudyName FROM Study WHERE StudyId>0
END
GO

GRANT EXECUTE ON [dbo].[GetStudyNames] TO [FastTrak]
GO