SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [ENDO].[GetApsType3]( @StudyId INT ) AS BEGIN EXEC ENDO.GetApsPatients @StudyId,3 END
GO

GRANT EXECUTE ON [ENDO].[GetApsType3] TO [FastTrak]
GO