SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [ENDO].[GetApsType1]( @StudyId INT ) AS BEGIN EXEC ENDO.GetApsPatients @StudyId,1 END
GO

GRANT EXECUTE ON [ENDO].[GetApsType1] TO [FastTrak]
GO