SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [ENDO].[GetApsType2]( @StudyId INT ) AS BEGIN EXEC ENDO.GetApsPatients @StudyId,2 END
GO

GRANT EXECUTE ON [ENDO].[GetApsType2] TO [FastTrak]
GO