SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [LAB].[GetLoincCodes] AS
BEGIN
	SELECT DISTINCT Loinc FROM dbo.LabClass WHERE Loinc IS NOT NULL;
END
GO

GRANT EXECUTE ON [LAB].[GetLoincCodes] TO [FastTrak]
GO