SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetType2WithBPAbove135]( @StudyId INT ) AS 
BEGIN
  EXECUTE NDV.GetType2WithHighBP @StudyId,135.1
END
GO

GRANT EXECUTE ON [NDV].[GetType2WithBPAbove135] TO [FastTrak]
GO