SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetGravide2015](  @StudyId INT )
AS
BEGIN
  EXEC NDV.GetPregnantByYear @StudyId,2015
END
GO

GRANT EXECUTE ON [NDV].[GetGravide2015] TO [FastTrak]
GO