SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetNonPumpAge0To21HbA1cAbove9]( @StudyId INT ) AS 
BEGIN
  EXECUTE NDV.GetNonPumpWithHighHbA1c @StudyId,0,21,9
END
GO

GRANT EXECUTE ON [NDV].[GetNonPumpAge0To21HbA1cAbove9] TO [FastTrak]
GO