SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetNonPumpHbA1cAbove7]( @StudyId INT ) AS 
BEGIN
  EXECUTE NDV.GetNonPumpWithHighHbA1c @StudyId,0,99,53.1
END
GO

GRANT EXECUTE ON [NDV].[GetNonPumpHbA1cAbove7] TO [FastTrak]
GO