SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetGravide2014](  @StudyId INT )
AS
BEGIN
  EXEC NDV.GetPregnantByYear @StudyId,2014
END
GO

GRANT EXECUTE ON [NDV].[GetGravide2014] TO [FastTrak]
GO