SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetType2WithLDLAbove35]( @StudyId INT ) AS 
BEGIN
  EXECUTE NDV.GetType2WithHighLDL @StudyId,3.51
END
GO

GRANT EXECUTE ON [NDV].[GetType2WithLDLAbove35] TO [FastTrak]
GO