SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetPumpAge21To25Hba1cAbove9]( @StudyId INT ) AS
BEGIN 
  EXECUTE NDV.GetPumpWithHighHbA1c @StudyId,21,26,75
END
GO

GRANT EXECUTE ON [NDV].[GetPumpAge21To25Hba1cAbove9] TO [FastTrak]
GO