SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetPumpHbA1cAbove7]( @StudyId INT ) AS 
BEGIN
  EXECUTE NDV.GetPumpWithHighHbA1c @StudyId,0,99,7.01
END
GO

GRANT EXECUTE ON [NDV].[GetPumpHbA1cAbove7] TO [FastTrak]
GO