SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetGravide2013](  @StudyId INT )
AS
BEGIN
  EXEC NDV.GetPregnantByYear @StudyId,2013
END
GO

GRANT EXECUTE ON [NDV].[GetGravide2013] TO [FastTrak]
GO