SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [NDV].[GetGravide2012](  @StudyId INT )
AS
BEGIN
  EXEC NDV.GetPregnantByYear @StudyId,2012
END
GO

GRANT EXECUTE ON [NDV].[GetGravide2012] TO [FastTrak]
GO