SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [PROM].[GetFormMapping]( @StudyId INT ) AS
BEGIN
	SELECT FormId, PromUid FROM PROM.FormMapping;
END
GO

GRANT EXECUTE ON [PROM].[GetFormMapping] TO [FastTrak]
GO