SET QUOTED_IDENTIFIER OFF

SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[GetListId]( @ListName VARCHAR(32) ) RETURNS INT
AS 
BEGIN
  DECLARE @ListId INT;
  SELECT @ListId = MAX(ListId) FROM MetaNomList WHERE ListName=@ListName AND LCID=1044 AND ListActive=1;
  RETURN @ListId;
END
GO