SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[DbCheckConstraintExists]( @ConstraintName NVARCHAR(128) ) RETURNS TINYINT
AS
BEGIN
  DECLARE @RetVal TINYINT;
  SELECT @RetVal = COUNT(*) FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS 
    WHERE CONSTRAINT_NAME = @ConstraintName;
  RETURN @RetVal;
END
GO