SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[AgeInYears]( @DateOfBirth DATETIME, @AgeOnDate DATETIME = NULL ) RETURNS INT AS
BEGIN
  SET @AgeOnDate = ISNULL( @AgeOnDate, GETDATE() );
  RETURN (CONVERT(INT,CONVERT(CHAR(8),GETDATE(),112))-CONVERT(CHAR(8),@DateOfBirth,112))/10000;
END
GO