SET QUOTED_IDENTIFIER OFF

SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[DbVersion]() RETURNS INT
AS
BEGIN
  DECLARE @DbVer INT;
  SELECT @DbVer = MAX(DbVer) FROM DbUpgradeLog WHERE NOT DbUpgradeEnd IS NULL;
  RETURN @DbVer
END
GO