SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [report].[StartOfMonth]( @SomeDate DateTime ) RETURNS DateTime AS
BEGIN
  RETURN DATEADD(MONTH, DATEDIFF(MONTH, 0, @SomeDate ), 0)
END
GO

GRANT EXECUTE ON [report].[StartOfMonth] TO [FastTrak]
GO