SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [report].[LabClassName]( @LabClassId INT ) RETURNS VARCHAR(8) AS
BEGIN
  RETURN FORMAT( @LabClassId, 'LAB0000#' );
END;
GO

GRANT EXECUTE ON [report].[LabClassName] TO [FastTrak]
GO