SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [report].[RowKeyReverse]( @TimeAxis DateTime ) RETURNS VARCHAR(6) AS
BEGIN
  RETURN CONVERT( VARCHAR, DATEDIFF( DD, @TimeAxis, '3000-01-01' ) );
END
GO